name: Build, Test & Deploy
on:
  push:
    branches: main
    paths-ignore:
      - '/.gitignore'
      - '/readme.md'
      - '/.tests'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pre-build
        shell: pwsh
        run: |
          Install-Module -Name msal.ps -Verbose -Scope CurrentUser -SkipPublisherCheck -Force -ErrorAction SilentlyContinue
          Install-Module Az.KeyVault -Verbose -Scope CurrentUser -SkipPublisherCheck  -Force -ErrorAction SilentlyContinue

      - name: build
        shell: pwsh
        run: |
          ./build.ps1

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./bin/release/*
          
      - name: Publish PowerShell Module
        # You may pin to the exact commit or the version.
        uses: pcgeek86/publish-powershell-module-action@2a7837ce0746ea58c40574d8d6cbc6c44238edb7
        with:
          # The filesystem path to the module to import into the environment.
          modulePath: ./bin/release/*
          # The NuGet API Key for PowerShell Gallery, with permission to push this module.
          NuGetApiKey: ${{ secrets.APIKEY }}
