name: Build, Test & Deploy
on:
  push:
    branches: main
    paths-ignore:
      - '/.gitignore'
      - '/readme.md'
      - '/.tests'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: pre-build
        shell: pwsh
        run: |
          Install-Module -Name msal.ps -Verbose -Scope CurrentUser -SkipPublisherCheck -Force -ErrorAction SilentlyContinue
          Install-Module Az.KeyVault -Verbose -Scope CurrentUser -SkipPublisherCheck  -Force -ErrorAction SilentlyContinue

      - name: build
        shell: pwsh
        run: |
          ./build.ps1

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./bin/release/*

      - name: Publish to Gallery
        shell: pwsh
        run: |
          try {
            write-host "Publishing module from: ${{ github.workspace }}\bin\release\ConfigMgr.AdminService"
            Publish-Module -Path "${{ github.workspace }}\bin\release\ConfigMgr.AdminService" -NuGetApiKey ${{ secrets.APIKEY }}
          }
          catch {
            write-warning $_
          }

